### ISSUE TITLE
NABirds Dataset Hierarchy 

### ISSUE THREAD

**Issue by 07Agarg** [cvjena/semantic-embeddings#6]
Thanks for the great work!

The `hierarchy.txt` given with the NABirds contains a mapping from 1010 to 555 categories. In your paper `Hierarchy-based Image Embeddings for Semantic Image Retrieval`, it is mentioned that 5 levels of deep hierarchy of those classes are provided with the dataset. 
I was curious to know how did you structure the hierarchies in `hierarchy.svg` for the NAbirds dataset ``` https://github.com/cvjena/semantic-embeddings/blob/master/NAB-Hierarchy/hierarchy.svg```?? 

Thanks in advance!

**Comment by Callidior** [comment]
Thank you for your interest and positive feedback!

The file [`hierarchy.txt`](https://github.com/cvjena/semantic-embeddings/blob/master/NAB-Hierarchy/hierarchy.txt) contains is-a tuples. For example, the line `1 0` means "class 1 is a sub-class of class 0". The names of the classes are provided in [`classes.txt`](https://github.com/cvjena/semantic-embeddings/blob/master/NAB-Hierarchy/classes.txt).

The visualization [`hierarchy.svg`](https://github.com/cvjena/semantic-embeddings/blob/master/NAB-Hierarchy/hierarchy.svg) has been created using the script [`plot_hierarchy.py`](https://github.com/cvjena/semantic-embeddings/blob/master/plot_hierarchy.py) in the root directory of this repository:

```bash
python plot_hierarchy.py --is_a \
    --hierarchy NAB-Hierarchy/hierarchy.txt \
    --class_names NAB-Hierarchy/classes.txt \
    --out NAB-Hierarchy/hierarchy.svg
```

**Comment by 07Agarg** [comment]
Yeah, I got it. Thanks for your response!
