### ISSUE TITLE
Issue when loading the model 

### ISSUE THREAD

**Issue by HikkaV** [cvjena/semantic-embeddings#7]
I tried to load the model imagenet_uni... and got the following error : 
AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'tf'
Maybe you can advice the solution, at least please emphasize the correct version of libraries to use. Thank you.

**Comment by Callidior** [comment]
Thanks for reaching out!
As stated in the README, the code was written using TensorFlow 1.8, way before the release of TF 2.
TensorFlow 2 introduced many backwards-incompatible changes, so the code in this repository will definitely not run with it. I will state this more clearly in the README.

Furthermore, you seem to be using the Keras bundled with TensorFlow (`tensorflow.keras`), while we used the stand-alone Keras.

In particular, we used the following versions of TensorFlow and Keras:
- tensorflow 1.8
- keras 2.2.4
- keras-applications 1.0.7
- keras-preprocessing 1.1.0

Others might work as well, as long as TF is below 2.0.

If the problem persists with the correct versions of TensorFlow and Keras, please post the code you are using to load the model.

**Comment by HikkaV** [comment]
Okay, thanks, I will try it out.

**Comment by HikkaV** [comment]
@Callidior , thanks! I've managed to load the model with tensorflow==1.15.0 and keras==2.2.4.
